name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Triggers the workflow when changes are pushed to the main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify Node.js version if needed

      - name: Build and deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Adjust if your HTML files are in a subdirectory
