name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to access code and content
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js to enable building static files (optional but useful for future extensions)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Choose the appropriate version if needed

      # Install dependencies if there are any (optional for static HTML but necessary if using tools like npm)
      # - run: npm install  # Uncomment if using a build process or dependencies

      # Build the website (optional, but useful if using static site generators)
      # - run: npm run build  # Uncomment if using a build command

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Adjust if your HTML files are within a specific directory
